Remove redundant grid_pos property from Graph
Due to https://github.com/crystal-lang/crystal/pull/9502 this throws an error now compiling with Crystal 0.36.0:
```
In src/crafana/models/panels/graph.cr:32:5

 32 | @[JSON::Field(key: "gridPos")]
      ^
Error: can't annotate @grid_pos in Crafana::Graph because it was first defined in Crafana::Panel
```

I'm not aware of any downsides of removing this duplicate definition.